<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>Warlords.Core</RootNamespace>
    <AssemblyTitle>Warlords</AssemblyTitle>
    <AssemblyProduct>Warlords</AssemblyProduct>
    <AssemblyDescription>Warlords: Iudicium Exodei Nefas - Soul Card Game</AssemblyDescription>
    <AssemblyCompany>CartBlanche</AssemblyCompany>
    <AssemblyCopyright>Copyright © CartBlanche 2025</AssemblyCopyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Authors>CartBlanche</Authors>
    <Company>CartBlanche</Company>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" PrivateAssets="all"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\1-Framework\Cards.Framework.csproj" />
    <ProjectReference Include="..\..\..\2-Core\Cards.Framework.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Warlords\**\*.cs" />
    <Compile Include="..\..\..\Framework\Warlords\**\*.cs" LinkBase="WarlordsFramework" />
  </ItemGroup>
</Project>
