//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blackjack.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession
        {
            get
            {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit this sample?.
        /// </summary>
        internal static string ConfirmExitSample
        {
            get
            {
                return ResourceManager.GetString("ConfirmExitSample", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the game,
        ///even though not all players are ready?.
        /// </summary>
        internal static string ConfirmForceStartGame
        {
            get
            {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession
        {
            get
            {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Online gameplay is not available in trial mode.
        ///Would you like to purchase this game?.
        /// </summary>
        internal static string ConfirmMarketplace
        {
            get
            {
                return ResourceManager.GetString("ConfirmMarketplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame
        {
            get
            {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string CreateSession
        {
            get
            {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession
        {
            get
            {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected
        {
            get
            {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must sign in a suitable gamer profile
        ///in order to access this functionality.
        /// </summary>
        internal static string ErrorGamerPrivilege
        {
            get
            {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession
        {
            get
            {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an error while
        ///accessing the network.
        /// </summary>
        internal static string ErrorNetwork
        {
            get
            {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Networking is turned
        ///off or not connected.
        /// </summary>
        internal static string ErrorNetworkNotAvailable
        {
            get
            {
                return ResourceManager.GetString("ErrorNetworkNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost
        {
            get
            {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This session is already full.
        /// </summary>
        internal static string ErrorSessionFull
        {
            get
            {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Session not found. It may have ended,
        ///or there may be no network connectivity
        ///between the local machine and session host.
        /// </summary>
        internal static string ErrorSessionNotFound
        {
            get
            {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must wait for the host to return to
        ///the lobby before you can join this session.
        /// </summary>
        internal static string ErrorSessionNotJoinable
        {
            get
            {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This functionality is not available in trial mode.
        /// </summary>
        internal static string ErrorTrialMode
        {
            get
            {
                return ResourceManager.GetString("ErrorTrialMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string ErrorUnknown
        {
            get
            {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit
        {
            get
            {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find Sessions.
        /// </summary>
        internal static string FindSessions
        {
            get
            {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (host).
        /// </summary>
        internal static string HostSuffix
        {
            get
            {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string JoinSession
        {
            get
            {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        internal static string LeaveSession
        {
            get
            {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading
        {
            get
            {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby
        {
            get
            {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu
        {
            get
            {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 
        ///A button, Space, Enter = ok
        ///B button, Esc = cancel.
        /// </summary>
        internal static string MessageBoxUsage
        {
            get
            {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} joined.
        /// </summary>
        internal static string MessageGamerJoined
        {
            get
            {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        internal static string MessageGamerLeft
        {
            get
            {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Networking....
        /// </summary>
        internal static string NetworkBusy
        {
            get
            {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No sessions found.
        /// </summary>
        internal static string NoSessionsFound
        {
            get
            {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused
        {
            get
            {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string PlayerMatch
        {
            get
            {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string QuitGame
        {
            get
            {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame
        {
            get
            {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby
        {
            get
            {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string SinglePlayer
        {
            get
            {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Link.
        /// </summary>
        internal static string SystemLink
        {
            get
            {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play
        {
            get
            {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme
        {
            get
            {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit
        {
            get
            {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host New Game.
        /// </summary>
        internal static string HostNewGame
        {
            get
            {
                return ResourceManager.GetString("HostNewGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh
        {
            get
            {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame
        {
            get
            {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Games:.
        /// </summary>
        internal static string AvailableGames
        {
            get
            {
                return ResourceManager.GetString("AvailableGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        internal static string Players
        {
            get
            {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        internal static string Deck
        {
            get
            {
                return ResourceManager.GetString("Deck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return
        {
            get
            {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for games....
        /// </summary>
        internal static string SearchingForGames
        {
            get
            {
                return ResourceManager.GetString("SearchingForGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} game{1}.
        /// </summary>
        internal static string FoundGames
        {
            get
            {
                return ResourceManager.GetString("FoundGames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-refresh in {0}s.
        /// </summary>
        internal static string AutoRefreshIn
        {
            get
            {
                return ResourceManager.GetString("AutoRefreshIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dealer: House.
        /// </summary>
        internal static string Dealer
        {
            get
            {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HOST.
        /// </summary>
        internal static string Host
        {
            get
            {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Slot {0}: {1}.
        /// </summary>
        internal static string Slot
        {
            get
            {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join or Host a Game.
        /// </summary>
        internal static string JoinOrHostGame
        {
            get
            {
                return ResourceManager.GetString("JoinOrHostGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create session..
        /// </summary>
        internal static string FailedToCreateSession
        {
            get
            {
                return ResourceManager.GetString("FailedToCreateSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to join session..
        /// </summary>
        internal static string FailedToJoinSession
        {
            get
            {
                return ResourceManager.GetString("FailedToJoinSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle
        {
            get
            {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DISPLAY.
        /// </summary>
        internal static string SettingsDisplay
        {
            get
            {
                return ResourceManager.GetString("SettingsDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AUDIO.
        /// </summary>
        internal static string SettingsAudio
        {
            get
            {
                return ResourceManager.GetString("SettingsAudio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NPC Players.
        /// </summary>
        internal static string SettingsNPCPlayers
        {
            get
            {
                return ResourceManager.GetString("SettingsNPCPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GAMEPLAY.
        /// </summary>
        internal static string SettingsGameplay
        {
            get
            {
                return ResourceManager.GetString("SettingsGameplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguage
        {
            get
            {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card Back Theme.
        /// </summary>
        internal static string SettingsCardBackTheme
        {
            get
            {
                return ResourceManager.GetString("SettingsCardBackTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string SettingsCurrency
        {
            get
            {
                return ResourceManager.GetString("SettingsCurrency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sound Volume.
        /// </summary>
        internal static string SettingsSoundVolume
        {
            get
            {
                return ResourceManager.GetString("SettingsSoundVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string SettingsMusicVolume
        {
            get
            {
                return ResourceManager.GetString("SettingsMusicVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max NPC Players.
        /// </summary>
        internal static string SettingsMaxNPCPlayers
        {
            get
            {
                return ResourceManager.GetString("SettingsMaxNPCPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fill Empty Slots.
        /// </summary>
        internal static string SettingsFillEmptySlots
        {
            get
            {
                return ResourceManager.GetString("SettingsFillEmptySlots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Animation Speed.
        /// </summary>
        internal static string SettingsAnimationSpeed
        {
            get
            {
                return ResourceManager.GetString("SettingsAnimationSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-Stand on 21.
        /// </summary>
        internal static string SettingsAutoStandOn21
        {
            get
            {
                return ResourceManager.GetString("SettingsAutoStandOn21", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Card Count.
        /// </summary>
        internal static string SettingsShowCardCount
        {
            get
            {
                return ResourceManager.GetString("SettingsShowCardCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Persist Winnings.
        /// </summary>
        internal static string SettingsPersistWinnings
        {
            get
            {
                return ResourceManager.GetString("SettingsPersistWinnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous
        {
            get
            {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next
        {
            get
            {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PageIndicator
        {
            get
            {
                return ResourceManager.GetString("PageIndicator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        internal static string Deal
        {
            get
            {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear
        {
            get
            {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        internal static string Hit
        {
            get
            {
                return ResourceManager.GetString("Hit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        internal static string Stand
        {
            get
            {
                return ResourceManager.GetString("Stand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string Double
        {
            get
            {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string Split
        {
            get
            {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string Insurance
        {
            get
            {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Hand.
        /// </summary>
        internal static string NewHand
        {
            get
            {
                return ResourceManager.GetString("NewHand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 1.
        /// </summary>
        internal static string NPCPlayer1
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 2.
        /// </summary>
        internal static string NPCPlayer2
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 3.
        /// </summary>
        internal static string NPCPlayer3
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 4.
        /// </summary>
        internal static string NPCPlayer4
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 5.
        /// </summary>
        internal static string NPCPlayer5
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized NPC player name 6.
        /// </summary>
        internal static string NPCPlayer6
        {
            get
            {
                return ResourceManager.GetString("NPCPlayer6", resourceCulture);
            }
        }
    }
}