<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Blank.Core</RootNamespace>
    <AssemblyTitle>Blank</AssemblyTitle>
    <AssemblyProduct>Blank</AssemblyProduct>
    <AssemblyDescription></AssemblyDescription>
    <AssemblyCompany>Microsoft</AssemblyCompany>
    <AssemblyCopyright>Copyright © Microsoft 2010</AssemblyCopyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Authors>CartBlanche</Authors>
    <Company>MonoGame Foundation</Company>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\1-Framework\Cards.Framework.csproj" />
    <ProjectReference Include="..\..\..\2-Core\Cards.Framework.Core.csproj" />
  </ItemGroup>
</Project>