<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Microsoft.Xna.Framework</RootNamespace>
    <AssemblyName>MonoGame.Xna.Framework.Net.Steam</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoGame.Xna.Framework.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" PrivateAssets="all" />
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>

</Project>
