<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CollisionSample.Core</AssemblyName>
    <RootNamespace>CollisionSample.Core</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <MonoGamePlatform>Native</MonoGamePlatform>
    <MonoGameBinariesPath Condition="'$(MonoGameBinariesPath)' == ''">$(MSBuildThisFileDirectory)..\..\MonoGame.3.8.4.2908-develop\MonoGame.Framework\</MonoGameBinariesPath>    
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>$(MonoGameBinariesPath)$(MonoGamePlatform)\MonoGame.Framework.dll</HintPath>
    </Reference>	
  </ItemGroup>

</Project>
