<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <RootNamespace>RacingGame</RootNamespace>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <MonoGameContentReference Include="..\Core\Content\RacingGameContent.mgcb">
      <Link>Content\RacingGameContent.mgcb</Link>
      <Platform>DesktopGL</Platform>
    </MonoGameContentReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-preview.3" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5-preview.3" />
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="CollectPackageReferences">
    <Message Text="Restoring dotnet tools..." Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>
