//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputReporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputReporterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputReporterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InputReporter.InputReporterResources", typeof(InputReporterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.A:.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.B:.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.Back:.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Left and Right Vibration Motors.
        /// </summary>
        internal static string BothVibrationMotors {
            get {
                return ResourceManager.GetString("BothVibrationMotors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed.
        /// </summary>
        internal static string ButtonPressed {
            get {
                return ResourceManager.GetString("ButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string ButtonReleased {
            get {
                return ResourceManager.GetString("ButtonReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold START to Change Dead Zone.
        /// </summary>
        internal static string DeadZoneInstructions {
            get {
                return ResourceManager.GetString("DeadZoneInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Disconnected).
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad.Down:.
        /// </summary>
        internal static string DPadDown {
            get {
                return ResourceManager.GetString("DPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad.Left:.
        /// </summary>
        internal static string DPadLeft {
            get {
                return ResourceManager.GetString("DPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad.Right:.
        /// </summary>
        internal static string DPadRight {
            get {
                return ResourceManager.GetString("DPadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad.Up:.
        /// </summary>
        internal static string DPadUp {
            get {
                return ResourceManager.GetString("DPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold BACK to Exit.
        /// </summary>
        internal static string ExitInstructions {
            get {
                return ResourceManager.GetString("ExitInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.LeftShoulder:.
        /// </summary>
        internal static string LeftShoulder {
            get {
                return ResourceManager.GetString("LeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.LeftStick:.
        /// </summary>
        internal static string LeftStick {
            get {
                return ResourceManager.GetString("LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbsticks.Left.X:.
        /// </summary>
        internal static string LeftThumbstickX {
            get {
                return ResourceManager.GetString("LeftThumbstickX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbsticks.Left.Y:.
        /// </summary>
        internal static string LeftThumbstickY {
            get {
                return ResourceManager.GetString("LeftThumbstickY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.Left:.
        /// </summary>
        internal static string LeftTrigger {
            get {
                return ResourceManager.GetString("LeftTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Left Vibration Motor Only.
        /// </summary>
        internal static string LeftVibrationMotor {
            get {
                return ResourceManager.GetString("LeftVibrationMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vibration Support.
        /// </summary>
        internal static string NoVibration {
            get {
                return ResourceManager.GetString("NoVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketNumber:.
        /// </summary>
        internal static string PacketNumber {
            get {
                return ResourceManager.GetString("PacketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.RightShoulder:.
        /// </summary>
        internal static string RightShoulder {
            get {
                return ResourceManager.GetString("RightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.RightStick:.
        /// </summary>
        internal static string RightStick {
            get {
                return ResourceManager.GetString("RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbsticks.Right.X:.
        /// </summary>
        internal static string RightThumbstickX {
            get {
                return ResourceManager.GetString("RightThumbstickX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbsticks.Right.Y:.
        /// </summary>
        internal static string RightThumbstickY {
            get {
                return ResourceManager.GetString("RightThumbstickY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.Right:.
        /// </summary>
        internal static string RightTrigger {
            get {
                return ResourceManager.GetString("RightTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Right Vibration Motor Only.
        /// </summary>
        internal static string RightVibrationMotor {
            get {
                return ResourceManager.GetString("RightVibrationMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.Start:.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller .
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.X:.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.Y:.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
